version: '3.8'
services:
  secureproxy:
    build: .

    volumes:
      - ./:/var/www/html
      - ./tmp:/tmp

    ports:
      - "80:80"

    container_name: secureproxy

    restart: unless-stopped 